apiVersion: v1
kind: Service
metadata:
  name: svc1
  labels: 
      app: java-maven-app
spec:
  selector:
    app: java-maven-app
  ports:
  - port: 8080
    nodePort: 30001
    protocol: TCP
  type: NodePort

